app_deployment:
  appName: auth-management-ui
  image: nexus-docker-craigmiller160.ddns.net/auth-management-ui:latest
  ports:
    - containerPort: 443
  commonProbe:
    httpGet:
      path: /healthcheck
      port: 443
      scheme: HTTPS
  secure_ingress:
    name: auth-management-ingress
    backendIsHttps: true
    hosts:
      - name: apps-craigmiller160.ddns.net
        services:
          - path: /(auth-management(/.*)?)
            serviceName: auth-management-ui
            portNumber: 443