app-deployment:
  appName: auth-management-ui
  image: nexus-docker-craigmiller160.ddns.net/auth-management-ui:latest
  ports:
    - containerPort: 443
  livenessProbe:
    httpGet:
      path: /healthcheck
      port: 443
      scheme: HTTPS